#!/bin/bash
ffmpeg -y -i $1 -vf fps=10,scale=1024:-1:flags=lanczos,palettegen /tmp/palette.png
ffmpeg -y -i $1 -i /tmp/palette.png -filter_complex "fps=10,scale=1024:-1:flags=lanczos[x];[x][1:v]paletteuse" $1.gif
